# Generated by Django 2.2.5 on 2019-09-16 21:17

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proofed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=250)),
                ('comment', models.CharField(max_length=500)),
                ('upload', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='EzeHersteller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hersteller_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='EzeTyp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=250)),
                ('project_number', models.BigIntegerField(default=0)),
                ('project_creation_date', models.DateTimeField(verbose_name='date published')),
                ('is_done', models.BooleanField(default=False)),
                ('access_for_user', models.BooleanField(default=False)),
                ('access_for_moderator', models.BooleanField(default=False)),
                ('access_for_admin', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EzeNeu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vDE_EZE1_Name', models.CharField(max_length=250)),
                ('vDE_EZE1_ZertNR', models.BigIntegerField(default=0)),
                ('vDE_EZE1_Motor', models.CharField(max_length=250)),
                ('vDE_EZE1_Generator', models.CharField(max_length=250)),
                ('vDE_EZE1_S', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('vDE_EZE1_P', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('vDE_Anzahl_EZE1', models.IntegerField(default=0)),
                ('eZeHersteller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification82.EzeHersteller')),
                ('eZeTyp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification82.EzeTyp')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification82.Project')),
            ],
        ),
        migrations.CreateModel(
            name='EzeBestand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vDE_EZE_Bestand_Zahl', models.IntegerField(default=0)),
                ('vDE_EZE_Name_ALT', models.CharField(max_length=250)),
                ('vDE_S_EZE_Alt', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('vDE_P_EZE_ALT', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('vDE_P_inbe_ALT', models.IntegerField(default=0)),
                ('eZeHersteller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification82.EzeHersteller')),
                ('eZeTyp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification82.EzeTyp')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification82.Project')),
            ],
        ),
    ]
