# Generated by Django 2.2.5 on 2019-09-22 16:25

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proofed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=250)),
                ('comment', models.CharField(max_length=500)),
                ('upload', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Eze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vDE_EZE1_Name', models.CharField(max_length=250)),
                ('vDE_EZE1_ZertNR', models.BigIntegerField(default=0)),
                ('vDE_EZE1_S', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('vDE_EZE1_P', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('vDE_Anzahl_EZE1', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EzeBestand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vDE_EZE_Bestand_Zahl', models.IntegerField(default=0)),
                ('vDE_EZE_Name_ALT', models.CharField(max_length=250)),
                ('vDE_S_EZE_Alt', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('vDE_P_EZE_ALT', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('vDE_P_inbe_ALT', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EzeHersteller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hersteller_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='EzeNeu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vDE_EZE1_Name', models.CharField(max_length=250)),
                ('vDE_EZE1_ZertNR', models.BigIntegerField(default=0)),
                ('vDE_EZE1_S', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('vDE_EZE1_P', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('vDE_Anzahl_EZE1', models.IntegerField(default=0)),
                ('vDE_EZE1_Motor', models.CharField(max_length=250)),
                ('vDE_EZE1_Generator', models.CharField(max_length=250)),
                ('eZeHersteller', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='certification82.EzeHersteller')),
            ],
        ),
        migrations.CreateModel(
            name='EzeTyp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=250)),
                ('project_number', models.BigIntegerField(default=0)),
                ('project_creation_date', models.DateTimeField(verbose_name='date published')),
                ('is_done', models.BooleanField(default=False)),
                ('access_for_user', models.BooleanField(default=False)),
                ('access_for_moderator', models.BooleanField(default=False)),
                ('access_for_admin', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EzeBestFotovoltaic',
            fields=[
                ('ezebestand_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='certification82.EzeBestand')),
                ('name', models.CharField(default=None, max_length=250)),
            ],
            bases=('certification82.ezebestand',),
        ),
        migrations.CreateModel(
            name='EzeBestGenerator',
            fields=[
                ('ezebestand_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='certification82.EzeBestand')),
                ('name', models.CharField(default=None, max_length=250)),
            ],
            bases=('certification82.ezebestand',),
        ),
        migrations.CreateModel(
            name='EzeBestWindkraft',
            fields=[
                ('ezebestand_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='certification82.EzeBestand')),
                ('name', models.CharField(default=None, max_length=250)),
            ],
            bases=('certification82.ezebestand',),
        ),
        migrations.CreateModel(
            name='EzeNeuFotovoltaic',
            fields=[
                ('eze_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='certification82.Eze')),
                ('name', models.CharField(default=None, max_length=250)),
            ],
            bases=('certification82.eze',),
        ),
        migrations.CreateModel(
            name='EzeNeuGenerator',
            fields=[
                ('ezeneu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='certification82.EzeNeu')),
                ('name', models.CharField(default=None, max_length=250)),
            ],
            bases=('certification82.ezeneu',),
        ),
        migrations.CreateModel(
            name='EzeNeuWindkraft',
            fields=[
                ('eze_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='certification82.Eze')),
                ('name', models.CharField(default=None, max_length=250)),
            ],
            bases=('certification82.eze',),
        ),
        migrations.AddField(
            model_name='ezeneu',
            name='eZeTyp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='certification82.EzeTyp'),
        ),
        migrations.AddField(
            model_name='ezeneu',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification82.Project'),
        ),
        migrations.AddField(
            model_name='ezebestand',
            name='eZeHersteller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification82.EzeHersteller'),
        ),
        migrations.AddField(
            model_name='ezebestand',
            name='eZeTyp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification82.EzeTyp'),
        ),
        migrations.AddField(
            model_name='ezebestand',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification82.Project'),
        ),
        migrations.AddField(
            model_name='eze',
            name='eZeHersteller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='certification82.EzeHersteller'),
        ),
        migrations.AddField(
            model_name='eze',
            name='eZeTyp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='certification82.EzeTyp'),
        ),
        migrations.AddField(
            model_name='eze',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification82.Project'),
        ),
    ]
