# Generated by Django 2.2.5 on 2019-09-15 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ezebestand',
            old_name='ezeTyp',
            new_name='eZeTyp',
        ),
        migrations.RenameField(
            model_name='ezebestand',
            old_name='hersteller',
            new_name='eZehersteller',
        ),
        migrations.RenameField(
            model_name='ezeneu',
            old_name='ezeTyp',
            new_name='eZeTyp',
        ),
    ]
