# Generated by Django 2.2.5 on 2019-09-23 21:23

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafoHersteller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No INFO', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TrafoTyp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No INFO', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Transformator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VDE_Trafo', models.CharField(default='No INFO', max_length=250)),
                ('VDE_TrafoUeber', models.CharField(default='No INFO', max_length=250)),
                ('VDE_TrafoOber', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('VDE_TrafoUnter', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('VDE_Trafo_kurz', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('VDE_Trafo_P', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('VDE_Trafohersteller', models.ForeignKey(default='No INFO', on_delete=django.db.models.deletion.CASCADE, to='certification82.TrafoHersteller')),
                ('VDE_Trafotyp', models.ForeignKey(default='No INFO', on_delete=django.db.models.deletion.CASCADE, to='certification82.TrafoTyp')),
            ],
        ),
    ]
