# Generated by Django 2.2.5 on 2019-10-17 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betreiber',
            name='login',
        ),
        migrations.RemoveField(
            model_name='betreiber',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='betreiber',
            name='password2',
        ),
    ]
