# Generated by Django 2.2.5 on 2019-10-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betreiber2',
            name='projekt_Nr',
            field=models.IntegerField(default=0),
        ),
    ]
