# Generated by Django 2.2.5 on 2019-10-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0002_auto_20191017_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='netzbetreiber',
            name='NB_AnsprechText',
            field=models.CharField(default='Netzbetreiber', max_length=250),
        ),
        migrations.AddField(
            model_name='netzbetreiber',
            name='NB_FaxText',
            field=models.CharField(default='Fax', max_length=250),
        ),
        migrations.AddField(
            model_name='netzbetreiber',
            name='NB_MailText',
            field=models.CharField(default='E-Mail', max_length=250),
        ),
        migrations.AddField(
            model_name='netzbetreiber',
            name='NB_NameText',
            field=models.CharField(default='Ansprechpartner NB', max_length=250),
        ),
        migrations.AddField(
            model_name='netzbetreiber',
            name='NB_PLZText',
            field=models.CharField(default='PLZ, Ort', max_length=250),
        ),
        migrations.AddField(
            model_name='netzbetreiber',
            name='NB_StrText',
            field=models.CharField(default='Straße', max_length=250),
        ),
        migrations.AddField(
            model_name='netzbetreiber',
            name='NB_TelText',
            field=models.CharField(default='Telefon', max_length=250),
        ),
        migrations.AddField(
            model_name='netzbetreiber',
            name='Projekt_NrText',
            field=models.CharField(default='Projekt_Nr', max_length=100),
        ),
    ]
