# Generated by Django 2.2.5 on 2019-10-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0003_auto_20191017_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='netzbetreiber',
            name='Registriernummer_NBText',
            field=models.CharField(default='Registrier Nummer NB', max_length=250),
        ),
        migrations.AddField(
            model_name='zertifikatsinhaber',
            name='EZA_BezeichnungText',
            field=models.CharField(default='Parkbezeichnung', max_length=100),
        ),
        migrations.AddField(
            model_name='zertifikatsinhaber',
            name='Projekt_NrText',
            field=models.CharField(default='Projektnummer', max_length=100),
        ),
        migrations.AddField(
            model_name='zertifikatsinhaber',
            name='Zert_FaxText',
            field=models.CharField(default='Fax', max_length=100),
        ),
        migrations.AddField(
            model_name='zertifikatsinhaber',
            name='Zert_FirmText',
            field=models.CharField(default='Ansprechpartner', max_length=100),
        ),
        migrations.AddField(
            model_name='zertifikatsinhaber',
            name='Zert_MailText',
            field=models.CharField(default='E-Mail', max_length=100),
        ),
        migrations.AddField(
            model_name='zertifikatsinhaber',
            name='Zert_NrText',
            field=models.CharField(default='Str, HausNr.', max_length=100),
        ),
        migrations.AddField(
            model_name='zertifikatsinhaber',
            name='Zert_PLZText',
            field=models.CharField(default='PLZ, Ort', max_length=100),
        ),
        migrations.AddField(
            model_name='zertifikatsinhaber',
            name='Zert_PartText',
            field=models.CharField(default='Firma', max_length=100),
        ),
        migrations.AddField(
            model_name='zertifikatsinhaber',
            name='Zert_TelText',
            field=models.CharField(default='Telefon', max_length=100),
        ),
        migrations.AlterField(
            model_name='netzbetreiber',
            name='Projekt_NrText',
            field=models.CharField(default='Projektnummer', max_length=100),
        ),
    ]
