# Generated by Django 2.2.5 on 2019-09-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0003_auto_20190915_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='ezeneu',
            name='eZeNeu_creation_date',
            field=models.DateTimeField(default='0', verbose_name='date published'),
        ),
    ]
