# Generated by Django 2.2.5 on 2019-10-06 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0003_auto_20191006_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='betreiber2',
            old_name='projekt_NrTexmarke',
            new_name='projekt_NrTextmarke',
        ),
        migrations.RenameField(
            model_name='betreiber2',
            old_name='projekttitelTexmarke',
            new_name='projekttitelTextmarke',
        ),
    ]
