# Generated by Django 2.2.5 on 2019-10-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0004_auto_20191017_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eze',
            name='eZeHersteller',
        ),
    ]
