# Generated by Django 2.2.5 on 2019-09-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0004_ezeneu_ezeneu_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ezeneu',
            name='eZeNeu_creation_date',
            field=models.DateTimeField(default='2019-01-01 12:12[:11[.000000]]', verbose_name='date published'),
        ),
    ]
