# Generated by Django 2.2.5 on 2019-09-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0004_auto_20190930_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ezeneu',
            name='EZA_Betreiber_AnspreTextmarke',
        ),
        migrations.RemoveField(
            model_name='ezeneu',
            name='Zert_PartTextmarke',
        ),
        migrations.AddField(
            model_name='project',
            name='EZA_Betreiber_AnspreTextmarke',
            field=models.CharField(default='EZA_Betreiber_Anspre', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='Zert_PartTextmarke',
            field=models.CharField(default='Zert_Part', max_length=100),
        ),
    ]
