# Generated by Django 2.2.5 on 2019-10-04 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0005_auto_20190930_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Netzbetreiber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NB_Ansprech', models.CharField(default='No INFO', max_length=250)),
                ('NB_Name', models.CharField(default='No INFO', max_length=250)),
                ('NB_Str', models.CharField(default='No INFO', max_length=250)),
                ('NB_PLZ', models.CharField(default='No INFO', max_length=250)),
                ('NB_Tel', models.CharField(default='No INFO', max_length=250)),
                ('NB_Fax', models.CharField(default='No INFO', max_length=250)),
                ('NB_Mail', models.CharField(default='No INFO', max_length=250)),
                ('NB_AnsprechTextmarke', models.CharField(default='NB_Ansprech', max_length=250)),
                ('NB_NameTextmarke', models.CharField(default='NB_Name', max_length=250)),
                ('NB_StrTextmarke', models.CharField(default='NB_Str', max_length=250)),
                ('NB_PLZTextmarke', models.CharField(default='NB_PLZ', max_length=250)),
                ('NB_TelTextmarke', models.CharField(default='NB_Tel', max_length=250)),
                ('NB_FaxTextmarke', models.CharField(default='NB_Fax', max_length=250)),
                ('NB_MailTextmarke', models.CharField(default='NB_Mail', max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='Registriernummer_NB',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Registriernummer_NBTextmarke',
            field=models.CharField(default='Registriernummer_NB', max_length=250),
        ),
        migrations.AddField(
            model_name='project',
            name='betreiberTextmarke',
            field=models.CharField(default='EZA_Betreiber_Anspre', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='netzbetreiberTextmarke',
            field=models.CharField(default='NB_Ansprech', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='netzbetreiber',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='certification82.Netzbetreiber'),
        ),
    ]
