# Generated by Django 2.2.5 on 2019-10-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('certification82', '0006_auto_20191009_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nameOK', models.BooleanField(default=False)),
                ('name', models.CharField(default='No INFO', max_length=250)),
                ('EZA_Betreiber_AnspreOK', models.BooleanField(default=False)),
                ('EZA_Betreiber_Anspre', models.CharField(default=' ', max_length=250)),
                ('EZA_Betreiber_StrNrOK', models.BooleanField(default=False)),
                ('EZA_Betreiber_StrNr', models.CharField(default=' ', max_length=250)),
                ('EZA_Betreiber_PlzOrtOK', models.BooleanField(default=False)),
                ('EZA_Betreiber_PlzOrt', models.CharField(default=' ', max_length=250)),
                ('EZA_Betreiber_TelOK', models.BooleanField(default=False)),
                ('EZA_Betreiber_Tel', models.CharField(default=' ', max_length=250)),
                ('EZA_Betreiber_MailOK', models.BooleanField(default=False)),
                ('EZA_Betreiber_Mail', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('anlagenzert_NrOK', models.BooleanField(default=False)),
                ('anlagenzert_Nr', models.CharField(default=' ', max_length=250)),
                ('projekt_NrOK', models.BooleanField(default=False)),
                ('projekt_Nr', models.IntegerField(default=0)),
                ('projekttitelOK', models.BooleanField(default=False)),
                ('projekttitel', models.CharField(default=' ', max_length=250)),
                ('EZA_Betreiber_AnspreTextmarke', models.CharField(default='EZA_Betreiber_Anspre', max_length=100)),
                ('EZA_Betreiber_NameTextmarke', models.CharField(default='EZA_Betreiber_Name', max_length=100)),
                ('EZA_Betreiber_StrNrTextmarke', models.CharField(default='EZA_Betreiber_StrNr', max_length=100)),
                ('EZA_Betreiber_PlzOrtTextmarke', models.CharField(default='EZA_Betreiber_PlzOrt', max_length=100)),
                ('EZA_Betreiber_TelTextmarke', models.CharField(default='EZA_Betreiber_Tel', max_length=100)),
                ('EZA_Betreiber_MailTextmarke', models.CharField(default='EZA_Betreiber_Mail', max_length=100)),
                ('anlagenzert_NrTextmarke', models.CharField(default='Anlagenzert_Nr', max_length=100)),
                ('projekt_NrTextmarke', models.CharField(default='Project_Nr', max_length=100)),
                ('projekttitelTextmarke', models.CharField(default='Projekttitel', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Betreiber2',
        ),
    ]
