# Generated by Django 2.2.5 on 2019-09-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0007_auto_20190915_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ezeneu',
            name='eZeNeu_creation_date',
            field=models.DateField(default='2019-01-01', verbose_name='date published'),
        ),
    ]
