# Generated by Django 2.2.5 on 2019-10-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0007_auto_20191005_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='betreiber',
            name='Projekt_Nr',
            field=models.BigIntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='betreiber',
            name='Projekt_NrTexmarke',
            field=models.CharField(default='Anlagenzert_Nr', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='betreiber',
            name='Projekttitel',
            field=models.CharField(default=' ', max_length=250),
        ),
        migrations.AddField(
            model_name='betreiber',
            name='ProjekttitelTexmarke',
            field=models.CharField(default='Anlagenzert_Nr', max_length=100, unique=True),
        ),
    ]
