# Generated by Django 2.2.5 on 2019-10-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0008_auto_20191005_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betreiber',
            name='Anlagenzert_NrTextmarke',
            field=models.CharField(default='Anlagenzert_Nr', max_length=100),
        ),
        migrations.AlterField(
            model_name='betreiber',
            name='EZA_Betreiber_AnspreTextmarke',
            field=models.CharField(default='EZA_Betreiber_Anspre', max_length=100),
        ),
        migrations.AlterField(
            model_name='betreiber',
            name='EZA_Betreiber_MailTextmarke',
            field=models.CharField(default='EZA_Betreiber_Mail', max_length=100),
        ),
        migrations.AlterField(
            model_name='betreiber',
            name='EZA_Betreiber_NameTextmarke',
            field=models.CharField(default='EZA_Betreiber_Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='betreiber',
            name='EZA_Betreiber_PlzOrtTextmarke',
            field=models.CharField(default='EZA_Betreiber_PlzOrt', max_length=100),
        ),
        migrations.AlterField(
            model_name='betreiber',
            name='EZA_Betreiber_StrNrTextmarke',
            field=models.CharField(default='EZA_Betreiber_StrNr', max_length=100),
        ),
        migrations.AlterField(
            model_name='betreiber',
            name='EZA_Betreiber_TelTextmarke',
            field=models.CharField(default='EZA_Betreiber_Tel', max_length=100),
        ),
    ]
