# Generated by Django 2.2.5 on 2019-10-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0009_auto_20191005_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betreiber',
            name='Projekt_Nr',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='betreiber',
            name='Projekt_NrTexmarke',
            field=models.CharField(default='Anlagenzert_Nr', max_length=100),
        ),
        migrations.AlterField(
            model_name='betreiber',
            name='ProjekttitelTexmarke',
            field=models.CharField(default='Anlagenzert_Nr', max_length=100),
        ),
    ]
