# Generated by Django 2.2.5 on 2019-10-09 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0010_auto_20191009_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betreiber',
            name='user',
        ),
        migrations.AddField(
            model_name='betreiber',
            name='projectuser',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
