# Generated by Django 2.2.5 on 2019-10-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0011_auto_20191009_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
