# Generated by Django 2.2.5 on 2019-10-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0013_auto_20191009_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='netzbetreiber',
            name='Registriernummer_NB',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='netzbetreiber',
            name='Registriernummer_NBTextmarke',
            field=models.CharField(default='Registriernummer_NB', max_length=250),
        ),
    ]
