# Generated by Django 2.2.5 on 2019-10-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0014_auto_20191009_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netzbetreiber',
            name='NB_Mail',
            field=models.EmailField(default='a@b.dfg', max_length=250),
        ),
    ]
