# Generated by Django 2.2.5 on 2019-10-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0015_auto_20191009_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netzbetreiber',
            name='Registriernummer_NB',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
