# Generated by Django 2.2.5 on 2019-10-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0016_auto_20191009_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='netzbetreiber',
            name='Projekt_Nr',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='netzbetreiber',
            name='Projekt_NrOK',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='netzbetreiber',
            name='Projekt_NrTextmarke',
            field=models.CharField(default='Projekt_Nr', max_length=100),
        ),
        migrations.AddField(
            model_name='zertifikatsinhaber',
            name='Projekt_Nr',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zertifikatsinhaber',
            name='Projekt_NrOK',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zertifikatsinhaber',
            name='Projekt_NrTextmarke',
            field=models.CharField(default='Projekt_Nr', max_length=100),
        ),
    ]
