# Generated by Django 2.2.5 on 2019-10-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0024_auto_20191012_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='comment',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='proofed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='upload',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='eze',
            name='VDE_EZE1_Generator',
            field=models.CharField(default='Keine Information', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eze',
            name='VDE_EZE1_Motor',
            field=models.CharField(default='Keine Information', max_length=100, null=True),
        ),
    ]
