# Generated by Django 2.2.5 on 2019-10-14 19:37

import certification82.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0025_auto_20191014_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='upload',
            field=models.FileField(default=1, storage=django.core.files.storage.FileSystemStorage(location='/media/pdf'), upload_to=certification82.models.user_directory_path),
            preserve_default=False,
        ),
    ]
