# Generated by Django 2.2.5 on 2019-10-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0029_auto_20191014_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='upload',
            field=models.FileField(upload_to=''),
        ),
    ]
