# Generated by Django 2.2.5 on 2019-10-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0002_auto_20191006_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betreiber2',
            name='projekt_NrTexmarke',
            field=models.CharField(default='Project_Nr', max_length=100),
        ),
        migrations.AlterField(
            model_name='betreiber2',
            name='projekttitelTexmarke',
            field=models.CharField(default='Projekttitel', max_length=100),
        ),
    ]
