# Generated by Django 2.2.5 on 2019-10-06 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0004_auto_20191006_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='betreiber',
            old_name='Projekt_NrTexmarke',
            new_name='Projekt_NrTextmarke',
        ),
        migrations.RenameField(
            model_name='betreiber',
            old_name='ProjekttitelTexmarke',
            new_name='ProjekttitelTextmarke',
        ),
    ]
