# Generated by Django 2.2.5 on 2019-10-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0008_user2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='EZA_Betreiber_Anspre',
        ),
        migrations.RemoveField(
            model_name='user',
            name='EZA_Betreiber_AnspreOK',
        ),
        migrations.RemoveField(
            model_name='user',
            name='EZA_Betreiber_AnspreTextmarke',
        ),
        migrations.RemoveField(
            model_name='user',
            name='EZA_Betreiber_Mail',
        ),
        migrations.RemoveField(
            model_name='user',
            name='EZA_Betreiber_MailOK',
        ),
        migrations.RemoveField(
            model_name='user',
            name='EZA_Betreiber_MailTextmarke',
        ),
        migrations.RemoveField(
            model_name='user',
            name='EZA_Betreiber_NameTextmarke',
        ),
        migrations.RemoveField(
            model_name='user',
            name='EZA_Betreiber_PlzOrt',
        ),
        migrations.RemoveField(
            model_name='user',
            name='EZA_Betreiber_PlzOrtOK',
        ),
        migrations.RemoveField(
            model_name='user',
            name='EZA_Betreiber_PlzOrtTextmarke',
        ),
        migrations.RemoveField(
            model_name='user',
            name='EZA_Betreiber_StrNr',
        ),
        migrations.RemoveField(
            model_name='user',
            name='EZA_Betreiber_StrNrOK',
        ),
        migrations.RemoveField(
            model_name='user',
            name='EZA_Betreiber_StrNrTextmarke',
        ),
        migrations.RemoveField(
            model_name='user',
            name='EZA_Betreiber_Tel',
        ),
        migrations.RemoveField(
            model_name='user',
            name='EZA_Betreiber_TelOK',
        ),
        migrations.RemoveField(
            model_name='user',
            name='EZA_Betreiber_TelTextmarke',
        ),
        migrations.RemoveField(
            model_name='user',
            name='anlagenzert_Nr',
        ),
        migrations.RemoveField(
            model_name='user',
            name='anlagenzert_NrOK',
        ),
        migrations.RemoveField(
            model_name='user',
            name='anlagenzert_NrTextmarke',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nameOK',
        ),
        migrations.RemoveField(
            model_name='user',
            name='projekt_NrOK',
        ),
        migrations.RemoveField(
            model_name='user',
            name='projekttitel',
        ),
        migrations.RemoveField(
            model_name='user',
            name='projekttitelOK',
        ),
        migrations.RemoveField(
            model_name='user',
            name='projekttitelTextmarke',
        ),
    ]
