# Generated by Django 2.2.5 on 2019-10-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0012_projectuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betreiber',
            name='Projekt_NrTextmarke',
            field=models.CharField(default='Projekt_Nr', max_length=100),
        ),
        migrations.AlterField(
            model_name='betreiber',
            name='ProjekttitelTextmarke',
            field=models.CharField(default='Projekttitel', max_length=100),
        ),
    ]
