# Generated by Django 2.2.5 on 2019-10-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0017_auto_20191010_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='netzbetreiber',
            name='Registriernummer_NBOK',
            field=models.BooleanField(default=False),
        ),
    ]
