# Generated by Django 2.2.5 on 2019-10-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0019_auto_20191010_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ezehersteller',
            name='hersteller_name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='ezetyp',
            name='typ_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
