# Generated by Django 2.2.5 on 2019-10-11 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0020_auto_20191010_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betreiber',
            name='projectuser',
        ),
    ]
