# Generated by Django 2.2.5 on 2019-10-11 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0021_remove_betreiber_projectuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='betreiber',
            name='projectuser',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
