# Generated by Django 2.2.5 on 2019-10-14 19:47

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0027_auto_20191014_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='upload',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/pdf'), upload_to='MEDIA_ROOT'),
        ),
    ]
