# Generated by Django 2.2.5 on 2019-10-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0030_auto_20191015_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformator',
            name='VDE_TrafoOberTextmarke',
            field=models.CharField(default='VDE_TrafoOber', max_length=250),
        ),
        migrations.AlterField(
            model_name='transformator',
            name='VDE_TrafoTextmarke',
            field=models.CharField(default='VDE_Trafo', max_length=250),
        ),
        migrations.AlterField(
            model_name='transformator',
            name='VDE_TrafoUeberTextmarke',
            field=models.CharField(default='VDE_TrafoUeber', max_length=250),
        ),
        migrations.AlterField(
            model_name='transformator',
            name='VDE_TrafoUnterTextmarke',
            field=models.CharField(default='VDE_TrafoUnter', max_length=250),
        ),
        migrations.AlterField(
            model_name='transformator',
            name='VDE_Trafo_PTextmarke',
            field=models.CharField(default='VDE_Trafo_P', max_length=250),
        ),
        migrations.AlterField(
            model_name='transformator',
            name='VDE_Trafo_kurzTextmarke',
            field=models.CharField(default='VDE_Trafo_kurz', max_length=250),
        ),
        migrations.AlterField(
            model_name='transformator',
            name='VDE_TrafoherstellerTextmarke',
            field=models.CharField(default='VDE_Trafohersteller', max_length=250),
        ),
        migrations.AlterField(
            model_name='transformator',
            name='VDE_TrafotypTextmarke',
            field=models.CharField(default='VDE_Trafotyp', max_length=250),
        ),
    ]
