# Generated by Django 2.2.5 on 2019-10-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0031_auto_20191015_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='upload_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
