# Generated by Django 2.2.5 on 2019-10-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification82', '0032_document_upload_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='upload_url',
        ),
    ]
